"""initial

Revision ID: 4e3df588d7ac
Revises: 
Create Date: 2026-05-10 11:57:15.972977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3df588d7ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('news_url_source_title_idx'), table_name='news')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "digest_subscribed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.alter_column("users", "digest_subscribed", server_default=None)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column("users", "digest_subscribed")
    op.drop_column('users', 'password_hash')
    op.create_index(op.f('news_url_source_title_idx'), 'news', ['url', 'source', 'title'], unique=False)
    # ### end Alembic commands ###
